Description: >
  Udacity cloud devops nano degree, second project.

Parameters:
  BastionSSHKey:
    Description: The name of the key used for the bastion host
    Type: String
  ApplicationSSHKey:
    Description: The name of the key used for the Application, it's left default once its no longer needed
    Type: String
  AvailabilityZoneA:
    Description: The first availability zone used in app deployment
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZoneB:
    Description: The first availability zone used in app deployment
    Type: AWS::EC2::AvailabilityZone::Name
Mappings:
  SubnetConfig:
    VPC:
      CIDR: "10.0.0.0/16"
    Public0:
      CIDR: "10.0.0.0/24"
    Public1:
      CIDR: "10.0.1.0/24"
    Private0:
      CIDR: "10.0.2.0/24"
    Private1:
      CIDR: "10.0.3.0/24"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap ["SubnetConfig", "VPC", "CIDR"]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"
  PrivateSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZoneA
      CidrBlock: !FindInMap ["SubnetConfig", "Private0", "CIDR"]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private-Subnet-0"
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZoneB
      CidrBlock: !FindInMap ["SubnetConfig", "Private1", "CIDR"]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private-Subnet-1"
  PublicSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZoneA
      VpcId: !Ref VPC
      CidrBlock: !FindInMap ["SubnetConfig", "Public0", "CIDR"]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public-Subnet-0"
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZoneB
      VpcId: !Ref VPC
      CidrBlock: !FindInMap ["SubnetConfig", "Public1", "CIDR"]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public-Subnet-1"
#Gateways then their attachments
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-InternetGateway"
          
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
  PublicNATGateway0:
    Type: "AWS::EC2::NatGateway"
    Properties:
      SubnetId: !Ref "PublicSubnet0"
      AllocationId: !GetAtt [ "NATElasticIP0", "AllocationId" ]
  PublicNATGateway1:
    Type: "AWS::EC2::NatGateway"
    Properties:
      SubnetId: !Ref "PublicSubnet1"
      AllocationId: !GetAtt [ "NATElasticIP1", "AllocationId" ]
#Routetables
  MainRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Main-Routetable"

  PrivateRouteTable0:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref "VPC"
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Private-Route-Table-0'
  PrivateRouteTable1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref "VPC"
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Private-Route-Table-1'
#The association between the routetables and their respective subnets
  PublicSubnet0MainRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MainRouteTable
      SubnetId: !Ref PublicSubnet0
  PublicSubnet1MainRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MainRouteTable
      SubnetId: !Ref PublicSubnet1
  PrivateSubnet0RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable0
      SubnetId: !Ref PrivateSubnet0
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1
#Routes and theis association to the route table

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref MainRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      
  PrivateRouteNatGateway0:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref "PrivateRouteTable0"
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref "PublicNATGateway0"
  PrivateRouteNatGateway1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref "PrivateRouteTable1"
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref "PublicNATGateway1"
#Autoscaling and its target group
  UbuntuAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchHTTPServerUbuntu
      MinSize: '4'
      MaxSize: '6'
      VPCZoneIdentifier: [!Ref PrivateSubnet0, !Ref PrivateSubnet1]
      TargetGroupARNs: [!Ref HTTPTargetGroup]
      BlockDeviceMappings:
        - DeviceName: "/dev/sdb"
          Ebs:
              VolumeSize: '10' #10GB
              DeleteOnTermination: true
      Tags:
          - Key: "Name"
            PropagateAtLaunch: false
            Value: !Sub '${AWS::StackName}-Ubuntu-HTTP-Autoscaling-Group'
  HTTPTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: HTTPTarget
      Port: 80
      Protocol: HTTP
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      VpcId: !Ref VPC
#Loadbalancer and its related settings
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      SecurityGroups: [!Ref LoadBalancerSecurityGroup]
      Subnets: [!Ref PublicSubnet0, !Ref PublicSubnet1]
      IpAddressType: "ipv4"
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Application-Loadbalancer'
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref HTTPTargetGroup
        LoadBalancerArn: !Ref ElasticLoadBalancer
        Protocol: HTTP
        Port: 80
  HTTPListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
          Actions:
          -   Type: forward
              TargetGroupArn: !Ref HTTPTargetGroup
          Conditions:
          -   Field: path-pattern
              Values: [/]
          ListenerArn: !Ref HTTPListener
          Priority: 1 
#Security Groups
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: allows any ip address to connect to our loadbalancers port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Loadbalancer-Security-Group'

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allows anyone to access the basion host ssh port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Bastion-Security-Group'

  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: allows anyone with route to this application to access its http and only bastion host to access its ssh port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      Tags:
          - Key: "Name"
            Value: !Sub '${AWS::StackName}-Application-HTTP-BastionSSH-Security-Group'
#Launch Configuration
  LaunchHTTPServerUbuntu: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          echo "it works! Udagram, Udacity" > /var/www/html/index.html
          echo "Datetime of creation: $(date)" >> /var/www/html/index.html
      ImageId: ami-0729e439b6769d6ab
      SecurityGroups: [!Ref ApplicationSecurityGroup]
      InstanceType: 't3.small'
#Elastic Ips
  NATElasticIP0:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
  NATElasticIP1:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
  BastionElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
#Ec2 instances
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0cff7528ff583bf9a'
      InstanceType: 't2.micro'
      KeyName: !Ref BastionSSHKey
      SubnetId: !Ref PublicSubnet0
      SecurityGroupIds: [!Ref BastionSecurityGroup]
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Bastion-Instance'
  BastionEIPAssocation:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      EIP: !Ref BastionElasticIP
      InstanceId: !Ref BastionInstance
Outputs:
  BastionPublicIp:
    Description: 'Bastion public ip'
    Value: !Sub '${BastionInstance.PublicIp}'
    Export:
      Name: BastionPublicIp
  LoadbalancerURL:
    Description: URL of the load balancer for quick access
    Value: !Sub "http://${ElasticLoadBalancer.DNSName}"
    Export:
      Name: !Sub ${AWS::StackName}-LoadBalancer-URL